export const menuItems = {
  engage: ["My Garage", "Watch List", "Inbox"],
  moreFromMarketplace: ["How it works", "Auction results"],
  insuranceProducts: [
    "1980 & newer collectors",
    "Antique tractors",
    "Classic & collector cars",
    "Military vehicles",
    "Modified vehicles",
    "Motorcycles & scooters",
    "Motorsport",
    "Trucks, Jeeps & SUVs",
    "Vintage camper trailers",
    "Boats & yachts",
  ],
  moreFromInsurance: [
    "Additional coverages",
    "Private client",
    "Business insurance",
    "Classic car financing",
    "Why Hagerty",
    "What vehicles qualify?",
    "Find a local agent",
  ],
  policyholders: [
    "Pay my bill",
    "Get ID cards",
    "View statements",
    "Manage policy",
  ],
  claims: ["File an auto claim", "Check on a claim", "Claims FAQ"],
  hagertyOriginals: [
    "ICONS w/ Jason Cammisa",
    "Revelations w/ Jason Cammisa",
    "Ultimate Drag Race Replay",
    "Barn Find Hunter",
    "The Driver's Seat w/ Henry Catchpole",
    "Capturing Car Culture w/ Larry Chen",
    "Redline/Redline Rebuild",
    "Will It Run?",
  ],
  categories: [
    "Auctions",
    "Automotive history",
    "Car Profiles",
    "Design",
    "Events",
    "Great Reads",
    "Hagerty Insider",
    "Maintenance and Tech",
    "Marketplace",
    "Member Stories",
    "Motorcycles",
    "New Car Reviews",
    "News",
    "Opinion",
    "People",
  ],
  popularVehicles: [
    "Camaro",
    "Corvette",
    "Mopar",
    "Muscle Cars",
    "Mustang",
    "Porsche",
    "Trucks",
  ],
  moreFromMedia: [
    "About us",
    "Contact us",
    "Drivers Club magazine",
    "Newsletters",
    "Partnerships",
  ],
  explore: [
    "Benefits",
    "Partner offers",
    "Magazine",
    "Exclusive events",
    "HDC Days",
  ],
  roadside: ["Roadside services", "888-310-8020"],
};
