import { type CarListing } from "~/types";

export const carListings: CarListing[] = [
  {
    id: "1",
    title: "1938 LaSalle Hearse",
    year: 1938,
    make: "LaSalle",
    model: "Hearse",
    price: 200000,
    location: {
      city: "San Marcos",
      state: "TX",
    },
    isAuction: false,
    isClassified: true,
    imageUrl: "/images/lasalle-hearse.jpg",
    dateListed: new Date("2024-02-20"),
  },
  {
    id: "2",
    title: "1968 Buick GS 350",
    year: 1968,
    make: "Buick",
    model: "GS 350",
    price: 9000,
    location: {
      city: "Bullhead",
      state: "AZ",
    },
    isAuction: true,
    isClassified: false,
    imageUrl: "/images/buick-gs.jpg",
    dateListed: new Date("2024-02-15"),
  },
  {
    id: "3",
    title: "1977 Buick Electra",
    year: 1977,
    make: "Buick",
    model: "Electra",
    price: 8000,
    location: {
      city: "Unionville",
      state: "MI",
    },
    isAuction: false,
    isClassified: true,
    imageUrl: "/images/buick-electra.jpg",
    dateListed: new Date("2024-02-18"),
  },
  {
    id: "4",
    title: "1964 Chevrolet El Camino",
    year: 1964,
    make: "Chevrolet",
    model: "El Camino",
    price: 20500,
    location: {
      city: "Steamboat Springs",
      state: "CO",
    },
    isAuction: false,
    isClassified: true,
    imageUrl: "/images/el-camino.jpg",
    dateListed: new Date("2024-02-17"),
  },
  {
    id: "5",
    title: "1959 Ford F-100",
    year: 1959,
    make: "Ford",
    model: "F-100",
    price: 25500,
    location: {
      city: "Rancho Cordova",
      state: "CA",
    },
    isAuction: false,
    isClassified: true,
    imageUrl: "/images/ford-f100.jpg",
    dateListed: new Date("2024-02-16"),
  },
  {
    id: "6",
    title: "2002 Chevrolet Camaro 35th Anniversary Edition",
    year: 2002,
    make: "Chevrolet",
    model: "Camaro",
    price: 29500,
    location: {
      city: "Castalian Springs",
      state: "TN",
    },
    isAuction: false,
    isClassified: true,
    imageUrl: "/images/camaro-35th.jpg",
    dateListed: new Date("2024-02-19"),
  },
  {
    id: "7",
    title: "2002 Honda S2000",
    year: 2002,
    make: "Honda",
    model: "S2000",
    price: 32000,
    location: {
      city: "Indianapolis",
      state: "IN",
    },
    isAuction: false,
    isClassified: true,
    imageUrl: "/images/honda-s2000.jpg",
    dateListed: new Date("2024-02-14"),
  },
  {
    id: "8",
    title: "1966 Ford Mustang Fastback Shelby GT350 Tribute Project",
    year: 1966,
    make: "Ford",
    model: "Mustang Fastback",
    price: 22250,
    location: {
      city: "Waukesha",
      state: "Wisconsin",
    },
    isAuction: true,
    isClassified: false,
    imageUrl: "/images/mustang-gt350.jpg",
    endDate: new Date("2024-03-01"),
    dateListed: new Date("2024-02-15"),
  },
  {
    id: "9",
    title: "1968 Ford Mustang",
    year: 1968,
    make: "Ford",
    model: "Mustang",
    price: 19800,
    location: {
      city: "Canton",
      state: "GA",
    },
    isAuction: false,
    isClassified: true,
    imageUrl: "/images/mustang-1968.jpg",
    dateListed: new Date("2024-02-13"),
  },
  {
    id: "10",
    title: "2007 Bentley Continental",
    year: 2007,
    make: "Bentley",
    model: "Continental",
    price: 90000,
    location: {
      city: "Las Vegas",
      state: "NV",
    },
    isAuction: false,
    isClassified: true,
    imageUrl: "/images/bentley.jpg",
    dateListed: new Date("2024-02-12"),
  },
  // Adding a few more from the images...
  {
    id: "11",
    title: "1970 CHEVROLET CHEVELLE",
    year: 1970,
    make: "Chevrolet",
    model: "Chevelle",
    price: 60000,
    location: {
      city: "Addison",
      state: "IL",
    },
    isAuction: false,
    isClassified: true,
    imageUrl: "/images/chevelle.jpg",
    dateListed: new Date("2024-02-11"),
  },
  {
    id: "12",
    title: "2001 Ferrari 360",
    year: 2001,
    make: "Ferrari",
    model: "360",
    price: 79500,
    location: {
      city: "Powell",
      state: "OH",
    },
    isAuction: false,
    isClassified: true,
    imageUrl: "/images/ferrari-360.jpg",
    dateListed: new Date("2024-02-10"),
  },
  {
    id: "13",
    title: "1980 Chevrolet Camaro",
    year: 1980,
    make: "Chevrolet",
    model: "Camaro",
    price: 15500,
    location: {
      city: "Anna",
      state: "TX",
    },
    isAuction: false,
    isClassified: true,
    imageUrl: "/images/camaro-1980.jpg",
    dateListed: new Date("2024-02-09"),
  },
  {
    id: "14",
    title: "1972 GMC 2500 Sierra Custom C",
    year: 1972,
    make: "GMC",
    model: "2500 Sierra Custom C",
    price: 29000,
    location: {
      city: "Canton",
      state: "GA",
    },
    isAuction: false,
    isClassified: true,
    imageUrl: "/images/gmc-sierra.jpg",
    dateListed: new Date("2024-02-08"),
  },
  {
    id: "15",
    title: "1983 Pontiac Firebird",
    year: 1983,
    make: "Pontiac",
    model: "Firebird",
    price: 19500,
    location: {
      city: "Daytona Beach",
      state: "FL",
    },
    isAuction: false,
    isClassified: true,
    imageUrl: "/images/pontiac-firebird.jpg",
    dateListed: new Date("2024-02-07"),
  },
  {
    id: "16",
    title: "1984 Toyota Pickup",
    year: 1984,
    make: "Toyota",
    model: "Pickup",
    price: 14500,
    location: {
      city: "Royston",
      state: "GA",
    },
    isAuction: false,
    isClassified: true,
    imageUrl: "/images/toyota-pickup.jpg",
    dateListed: new Date("2024-02-06"),
  },
  {
    id: "17",
    title: "1957 Chevrolet Bel Air",
    year: 1957,
    make: "Chevrolet",
    model: "Bel Air",
    price: 40000,
    location: {
      city: "Ashland",
      state: "IL",
    },
    isAuction: false,
    isClassified: true,
    imageUrl: "/images/bel-air.jpg",
    dateListed: new Date("2024-02-05"),
  },
  {
    id: "18",
    title: "1948 Chrysler Town & Country",
    year: 1948,
    make: "Chrysler",
    model: "Town & Country",
    price: 160000,
    location: {
      city: "Fort Lauderdale",
      state: "FL",
    },
    isAuction: false,
    isClassified: true,
    imageUrl: "/images/chrysler-town-country.jpg",
    dateListed: new Date("2024-02-04"),
  },
  {
    id: "19",
    title: "1966 Ford Mustang",
    year: 1966,
    make: "Ford",
    model: "Mustang",
    price: 38000,
    location: {
      city: "Brick",
      state: "NJ",
    },
    isAuction: false,
    isClassified: true,
    imageUrl: "/images/mustang-1966.jpg",
    dateListed: new Date("2024-02-03"),
  },
  {
    id: "20",
    title: "1974 Toyota Land Cruiser",
    year: 1974,
    make: "Toyota",
    model: "Land Cruiser",
    price: 51000,
    location: {
      city: "Austin",
      state: "TX",
    },
    isAuction: false,
    isClassified: true,
    imageUrl: "/images/land-cruiser.jpg",
    dateListed: new Date("2024-02-02"),
  },
];
